/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lei_jni_demo_Jni_Test */

#ifndef _Included_com_lei_jni_demo_Jni_Test
#define _Included_com_lei_jni_demo_Jni_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lei_jni_demo_Jni_Test
 * Method:    getData
 * Signature: ([CII)D
 */
JNIEXPORT jdouble JNICALL Java_com_lei_jni_1demo_Jni_1Test_getData
  (JNIEnv *, jclass, jcharArray, jint, jint);

/*
 * Class:     com_lei_jni_demo_Jni_Test
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lei_jni_1demo_Jni_1Test_getInt
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
